# SPDX-FileCopyrightText: 2020 tech@factchecklab <tech@factchecklab.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.6'
services:
  web:
    build:
      context: .
    command: yarn dev
    ports:
    - 3000:3000
    volumes:
      - ./:/usr/src/app
    environment:
      - GRAPHQL_HTTP_ENDPOINT=http://host.docker.internal:4000
      - GRAPHQL_BROWSER_HTTP_ENDPOINT=http://localhost:4000

    # See docker/for-linux#264. For Docker 19.03 or before, change host-gateway
    # to your host IP.
    #extra_hosts:
    #  - http://host.docker.internal:host-gateway
